[tool.black]
line-length = 122
target-version = ['py36', 'py37', 'py38', 'py39']
experimental_string_processing = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 122

[tool.autoflake]
check = true
imports = ["django", "requests", "urllib3"]
remove-all-unused-imports = true
